#!/usr/bin/env python3
"""Assemble the Project DD cloud bundle from the local app/ (single source of truth).

The local app/ directory is the ONLY place Project DD is authored. This script
copies the four shared static files verbatim into cloud/ and writes a cloud
config.js that flips DD_CLOUD on (which hides the local-only "Refresh now" button).
Run it before every cloud deploy so the Databricks App stays in perfect parity with
the local app — any local change, UI or data, propagates on the next build+deploy.

server.py and app.yaml are permanent files in this directory and are left untouched.

    python3 cloud/build_cloud.py
"""
import datetime
import os
import shutil

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
APP = os.path.join(ROOT, "app")
SHARED = ["index.html", "app.js", "styles.css", "data.js"]
# hygiene_data.js feeds the Hygiene module and is written by a DIFFERENT pipeline
# (an optional add-on). rob_content.js is the hand-curated review narrative. Both are optional: a
# hygiene build that failed must not block a Project DD publish. When it is absent
# from app/ we leave whatever is already staged here, so the cloud keeps showing
# the last real scores instead of an empty module.
OPTIONAL = ["hygiene_data.js", "rob_content.js"]


# Google Drive / Finder drop a 0-byte custom-folder-icon file literally named
# "Icon\r" into synced folders. `databricks sync` tries to PUT it, and the
# carriage return makes an illegal workspace path -> HTTP 400 "Invalid request
# path", which aborts the ENTIRE sync (so no fresh data.js ever lands). The CLI's
# --exclude matcher does not reliably honour a literal CR in the pattern, so the
# only dependable fix is to delete the artifacts here, immediately before sync.
DRIVE_ARTIFACTS = ("Icon\r", ".DS_Store")


def purge_drive_artifacts():
    removed = []
    for name in os.listdir(HERE):
        if name in DRIVE_ARTIFACTS:
            try:
                os.remove(os.path.join(HERE, name))
                removed.append(repr(name))
            except OSError:
                pass
    return removed


def main():
    purged = purge_drive_artifacts()

    missing = [f for f in SHARED if not os.path.exists(os.path.join(APP, f))]
    if missing:
        raise SystemExit(f"build_cloud: missing source files in app/: {missing}")

    for f in SHARED:
        shutil.copy2(os.path.join(APP, f), os.path.join(HERE, f))

    staged_opt, skipped_opt = [], []
    for f in OPTIONAL:
        src = os.path.join(APP, f)
        if os.path.exists(src):
            shutil.copy2(src, os.path.join(HERE, f))
            staged_opt.append(f)
        else:
            skipped_opt.append(f + (" (kept staged copy)" if os.path.exists(os.path.join(HERE, f)) else " (absent)"))

    ts = datetime.datetime.now().astimezone().isoformat(timespec="seconds")
    with open(os.path.join(HERE, "config.js"), "w") as fh:
        fh.write(
            "// GENERATED by build_cloud.py — do not edit. Cloud mirror flag.\n"
            "window.DD_CLOUD=true;\n"
            f'window.DD_DEPLOY_TS="{ts}";\n'
        )

    staged = SHARED + staged_opt
    total = sum(os.path.getsize(os.path.join(HERE, f)) for f in staged)
    note = f" | purged {', '.join(purged)}" if purged else ""
    if skipped_opt:
        note += f" | no fresh {', '.join(skipped_opt)}"
    print(f"build_cloud: staged {len(staged)} files ({total // 1024} KB) + config.js @ {ts}{note}")


if __name__ == "__main__":
    main()
